title: Technocom Co
email: ivana.p.kostova@gmail.com
description: Technocom Co
destination: docs
baseurl: "" # the subpath of your site
baseurl: "/technocom" # the subpath of your site
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  pneumatics:
    output: true
  transport-systems:
    output: true
  news:
    output: true
collections_dir: collections
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  # - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
